### ISSUE TITLE
[not really an issue] jtc is available in Fedora's repositories

### ISSUE THREAD

**Issue by D4N** [ldn-softdev/jtc#13]
Hi @ldn-softdev, I've packaged jtc for Fedora and submitted it to the repositories for Rawhide and Fedora 31 (it will take ~ a week for it to hit the Fedora 31 repos though).

This is more of an FYI-issue, but I can submit a PR to the README with added installation instructions? Otherwise, feel free to close this and thanks for creating jtc!

**Comment by ldn-softdev** [comment]
Hi D4N!
thank you very much, any contribution is more than welcome, please, go ahead and submit a PR, I'll merge it.
Though in my next rebuild 1.75d (improvements/minor fixes only , no new features - `jtc` by now covers almost any use-case, I have drastically improved performance of `<>g`/`<>G` lexemes - now they are as fast as bare metal sort) which I'm going to publish very soon, so you might want to repackage it with that newer rebuild.

**Comment by ldn-softdev** [comment]
Hi D4N,
I have published now probably the final update for `jtc`, please go and file the PR with the install instructions for Fedora., I'll merge it. Thank you in advance!
