### ISSUE TITLE
[FreeBSD] Fails to compile with -DBG_CC

### ISSUE THREAD

**Issue by bsdlcook** [ldn-softdev/jtc#19]
Since the latest version (1.76), toggling -DBG_CC will throw an error:

```
lib/Json.hpp:691:50: error: no member named 'ind' in '__Dbg_flow__'
                          if(DBG()(__Dbg_flow__::ind)) {        // dodge DBG's mutex dead-lock

lib/Json.hpp:695:65: error: no member named 'ind' in '__Dbg_flow__'
                                                  __Dbg_flow__::ind + 1, DBG().stamped(),
```

As the error suggests there's no member named ``ind`` in the ``__Dbg_flow__`` class, but rather ``ind_`` seen at [dbg.hpp#L886](https://github.com/ldn-softdev/jtc/blob/master/lib/dbg.hpp#L886) which is also a protected member. Either a new member could be exposed as public or to make ``ind_`` public (although not ideal) — simple fix nonetheless. Thanks for your time on this project, cheers!

**Comment by ldn-softdev** [comment]
Hi, thanks for reporting and catching this one, let me publish a quick fix for this one.
