### ISSUE TITLE
[FreeBSD] Fails to build with clang 10

### ISSUE THREAD

**Issue by bsdlcook** [ldn-softdev/jtc#20]
Since clang 10, the compiler has been made more restrictive in what is allowed. As a result of this an error is thrown during compilation with clang 10:

```
./lib/Json.hpp:1224:37: error: cannot assign to non-static data member within const member function 'operator()'
                             { lbp_ = &s; jnp_ = &jn; return *this; }
                               ~~~~ ^
./lib/Json.hpp:1223:29: note: member function 'Jnode::Iterator::SuperJnode::operator()' is declared const here
        const SuperJnode &  operator()(const std::string &s, const Jnode &jn) const
        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./lib/Json.hpp:1224:48: error: cannot assign to non-static data member within const member function 'operator()'
                             { lbp_ = &s; jnp_ = &jn; return *this; }
                                          ~~~~ ^
./lib/Json.hpp:1223:29: note: member function 'Jnode::Iterator::SuperJnode::operator()' is declared const here
        const SuperJnode &  operator()(const std::string &s, const Jnode &jn) const
        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Outright removing this line at [Json.hpp#L1223](https://github.com/ldn-softdev/jtc/blob/master/lib/Json.hpp#L1223]) resolves the issue, if this was intentional I don't know. Cheers!

**Comment by ldn-softdev** [comment]
Actually, it's a good improvement on the compiler end, I agree, for now it would not cause a bug (with the given logic) but for a safety of the code it's better to rework this one. Will do and publish the fix along with the previously reported. Thank you very much for trying with the latest version of the clang.

**Comment by ldn-softdev** [comment]
I pushed an update for the both reported issues. Thank you very much again for catching those.
