### ISSUE TITLE
url for precompiled binaries is wrong

### ISSUE THREAD

**Issue by soniah** [ldn-softdev/jtc#25]
url is https://github.com/ldn-softdev/jtc/releases/download/LatestBuild/jtc-linux-64.latest, which causes a `.latest` file to be downloaded, rather than a `.zip`

**Comment by ldn-softdev** [comment]
Soniah,
I'm sorry, I'm not sure I follow you right. The intention for the link was to point to the _latest binary_ - as per the description:
>#### Linux and MacOS precompiled binaries are available for download
>or download the latest **precompiled binary**:

so the link points to the latest binary and downloads it. The link for the latest (master) `.zip` is in the section:
> #### Manual installation:
>download [`jtc-master.zip`](https://github.com/ldn-softdev/jtc/archive/master.zip), unzip it, descend into unzipped folder, compile using an appropriate command, move compiled file into an install location.


Am I missing something?

**Comment by soniah** [comment]
![Image 5-6-20 at 10 06](https://user-images.githubusercontent.com/56102/83822513-989f9080-a714-11ea-8db4-358bfe0302ea.jpeg)

**Comment by ldn-softdev** [comment]
I see where confusion is. Files `.latest` are the binaries. You just need to rename it and give execution permissions, like this:
```
mv jtc-linux-64.latest jtc
chmod 754 jtc
```

Probably it would be more descriptive, if I give them `.bin` extensions?

**Comment by ldn-softdev** [comment]
I cannot name all 3 files (for MacOs, Linux 64bit, and 32bit) just `jtc` and keep all 3 in the same location (likewise it's impossible to have 3 different files under the same name in one folder).

Instead, I'll add instructions like I mentioned above (to rename the file and give exec permissions).
