### ISSUE TITLE
<<<'[ "1st json" ] { "2nd": "json" } "3rd json"' jtc -ar dies with a failed assertion or an exception

### ISSUE THREAD

**Issue by D4N** [ldn-softdev/jtc#29]
The following example from the user guide results in a failed assertion:
```ShellSession
$ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
/builddir/build/BUILD/gcc-10.1.1-20200507/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1019: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```
This does only happen with gcc though, with clang I get the following instead:
```ShellSession
$ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
jtc json parsing exception (<stdin>:44): expected_json_value
```

**Comment by ldn-softdev** [comment]
D4N, what was your complete compile line?
I noticed already that when compiled with sanitizer it sometimes alters the input's endings (maybe for some internal purposes) which does not normally happen when image is compiled normally, which may result then in such exception. The same exception/assertion would not occur if `jtc` is built using normal options.  Let me know.
In such case, those tests you may mark with a `SKIP` tag.

**Comment by D4N** [comment]
I was probably quite sleepy when I wrote this issue, because now when I retry it, I get this instead:
``` ShellSession
$ g++ -o jtc -g3 -O2 -Wall -Wextra -std=gnu++14  -pthread -lpthread jtc.cpp
$ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
jtc json parsing exception (<stdin>:44): expected_json_value
$ g++ -o jtc -Wall -Wextra -std=gnu++14 -fsanitize=address,undefined -fno-omit-frame-pointer  -pthread -lpthread jtc.cpp
$ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
jtc json parsing exception (<stdin>:44): expected_json_value
$ g++ -o jtc -O2 -Wall -Wextra -std=gnu++14 -fsanitize=address,undefined -fno-omit-frame-pointer  -pthread -lpthread jtc.cpp
$ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
jtc json parsing exception (<stdin>:44): expected_json_value
```
The parsing exception is still occurring though, even without ASAN+UBSAN.

**Comment by ldn-softdev** [comment]
On my linux, I can reproduce that exception only if sanitizers are on (ASAN+UBSAN) *and* any of optimizations (`-O1`, `-O2`, etc). Without either - it's working just fine. Let me take a look once again, why that combination is resulting in such rogue trailing char detection.

However, for the test purposes - it should not be a show stopper, as all the exceptions are printed into the `<stderr>` only, e.g.:
```
bash $ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
jtc json parsing exception (<stdin>:44): expected_json_value
bash $ <<<'[ "1st json" ] { "2nd": "json" } "3rd json"' ./jtc -ar 2>/dev/null
[ "1st json" ]
{ "2nd": "json" }
"3rd json"
bash $ 
```

**Comment by D4N** [comment]
Dmitry Lyssenko <notifications@github.com> writes:

> On my linux, I can reproduce that exception only if sanitizers are on (ASAN+UBSAN) *and* any of optimizations (`-O1`, `-O2`, etc). Without either - it's working just fine. Let me take a look once again, why that combination is resulting in such rogue trailing char detection.
>

Out of curiosity, which version of gcc are you using on your box?

**Comment by ldn-softdev** [comment]
0n my mac it's 4.2.1:
```
bash $ c++ -dumpversion
4.2.1
```
on my linux box it's 7:
```
bash:~$ g++ -dumpversion
7
```

**Comment by ldn-softdev** [comment]
D4N,
I think I have nailed the problem with `-a` and multiple JSONs at the input producing `expected_json_value ` exception - I have committed the fix. Could you please try and let me know if you don't observe that exception any longer on your system?

I also fixed another issue with the `$PATH` auto-token, one we discussed in your pull request.
