### ISSUE TITLE
[not a issue]Thanks

### ISSUE THREAD

**Issue by Obarun** [ldn-softdev/jtc#3]
Hi there,

Thanks so much for this works.
It took me a while to find an another JSON parser than jq (horrible one).
Your API is simple to understand, simple to use,so quick and do the works perflectly.

This is now implemented by default on my distribution (obarun.org)

Best Regards.

Eric Vidal

**Comment by ldn-softdev** [comment]
I'm happy you liked it. `jtc` indeed was released not so long ago, it's relatively new and not widely known yet.
It's nice to receive feedbacks like yours, making me being sure that I haven't wasted my time and efforts for nothing creating `jtc`.

**Comment by Obarun** [comment]
Often, the best is the less know.
