### ISSUE TITLE
more documentation on -i0

### ISSUE THREAD

**Issue by soniah** [ldn-softdev/jtc#30]
Looking at this example given when running `jtc -g`:

`jtc -fw'[Relation][:]<g:"X">f<\bSmith\b>R<g:"Y">v[-1]' -i0 -T'{"gene": "{g}"}' example.json`

There doesn't seem to be a clear explanation of `-i0` in the documentation.

If I do `jtc -h` there's this:

`-i j|w|t       insert JSON (given as JSON/walk/template); see with -g for more`

I'm guessing `0` is a walk? But then there's the `-T` that is a template.

I've tried running this through the debugger (`-dddd`) but the debugging output seems focussed on the walk-path.

And this doesn't clarify either: https://github.com/ldn-softdev/jtc/blob/master/User%20Guide.md#insert-operations

**Comment by ldn-softdev** [comment]
Yes, I'll update that point as well, thanks for the feedback.

Before version _v1.76_, the options like `-i`, `-u`, `-c` were accepting only 2 kinds of argument:
1. `JSON` (spelled literally, or read from a file)
2. `walk`

In the example, the template (`-T'{"gene": "{g}"}'`) is getting applied onto the _insertion argument_ (`-i0`), however, the argument itself is irrelevant - it's not getting interpolated in that template, hence a _dummy JSON_ is used. `0` (argument of `-i`) it's a number, like any numeric JSON it's a rudimentary but still a valid JSON.

starting from _v.176_ all those options now can support templates as argument as well, thus the whole command could be collapsed into:
```
jtc -w'[Relation][:]<g:"X">f<\bSmith\b>R<g:"Y">v[-1]' -i'{"gene": "{g}"};' example.json
```
> the trailing `;` is required to distinguish between a JSON argument and the template:
> - JSON (as an argument of `-i`/`-u`/`-c`) does not tolerate any trailing characters (thus if spelled w/o `;`, `jtc` would recognize it as a JSON rather than a template)
> - while the templates arguments (in `-i`/`-u`/`-c`) can tolerate any trailing characters (JSON parsing simply would ignore any trailing chars after parsing)

The [argument disambiguation logic](https://github.com/ldn-softdev/jtc/blob/master/User%20Guide.md#argument-disambiguation-path) is described in the User Guide.

**Comment by soniah** [comment]
I'm learning, thanks for all your help :-)

https://stackoverflow.com/questions/62421111/parse-json-and-iterate-objects-using-jq/62421373#62421373

**Comment by ldn-softdev** [comment]
Nice answer, couple points:
1. `-r` serves there a better purpose than `-tc`:
    - `-r` _ensures_ that walk will be printed one-line _always_
    - while `-tc` only prints it one-line if there are no nested iterable structures (like nested arrays and objects) - otherwise, if `metadata` were holding non-empty `[..]`, or `{..}` those wouldn't be printed in one-line (`-tc` stand for semi-compact printing, while `-r` stands for "raw" - single row)
2. the default benefit you get with `jtc` solutions is that most of them are _input invariant_: i.e., add any outer encapsulation to the source JSON in the example and your `jtc` solution will still work. While all given `jq` solutions fail - that makes `jtc` solutions more robust and tolerant to JSON structure changes.
