### ISSUE TITLE
Doesn't compile on Arch (Garuda)

### ISSUE THREAD

**Issue by sxiii** [ldn-softdev/jtc#36]
<details><summary>uname -a</summary>

```
Linux rog-strix 5.19.0-rc7-1-mainline #1 SMP PREEMPT_DYNAMIC Mon, 18 Jul 2022 10:35:36 +0000 x86_64 GNU/Linux
```

</details>

<details><summary>lsb_release -a</summary>

```
LSB Version:	n/a
Distributor ID:	Garuda
Description:	Garuda Linux
Release:	Soaring
Codename:	Talon
```

</details>

Let me know how I can provide error log if this can be helpful. The "jtm" utility compiled & works OK on Arch.

**Comment by dlyssenko** [comment]
Hi @sxiii, could you please paste into this thread the compile line you use and the complete output?

**Comment by sxiii** [comment]
Tried again with the latest version (of my system) -> and now it works. Sorry for bothering :)
